services:
  backend:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql:8.3.0"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./scripts/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jun@2024