services:
  backend:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "mysql:8.3.0"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Jan@2019