services:
  backend:
    build: .
    ports:
      - "8080:8080"
    secrets:
      - db_password
  db:
    image: "mysql:8.3.0"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
        - ./scripts/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
secrets:
  db_password:
    file: ./ToDo_List_db_passwd